# Generated by Django 4.1.3 on 2022-12-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://platerate.com/images/tempfoodnotext.png', max_length=500),
        ),
    ]
